<?php

namespace ReparationBundle\Repository;

/**
 * PiecesdefectueusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecesdefectueusesRepository extends \Doctrine\ORM\EntityRepository
{
}
