<?php

namespace ReparationBundle\Repository;

/**
 * PiecesdefectueusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecesdefectueusesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDefective(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ReparationBundle:Piecesdefectueuses p
                WHERE p.reserved =:yep'
            )
            ->setParameter('yep', false)
            ->getResult();


    }
}
