<?php

namespace ReparationBundle\Repository;

/**
 * ReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparationRepository extends \Doctrine\ORM\EntityRepository
{
}
