<?php

namespace ServiceBundle\Repository;

/**
 * MoyenDeTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenDeTransportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l
                FROM ServiceBundle:MoyenDeTransport l
                WHERE l.marque LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
