<?php

namespace ServiceBundle\Repository;

/**
 * MoyenDeTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenDeTransportRepository extends \Doctrine\ORM\EntityRepository
{
}
