<?php

namespace ServiceBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservations($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l
                FROM ServiceBundle:Reservation l
                WHERE l.Hebergement =:id AND (l.dateArrivee + l.nbJours)> CURRENT_DATE() ORDER BY l.dateArrivee'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
