<?php

namespace EventsBundle\Repository;

/**
 * PublicityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicityRepository extends \Doctrine\ORM\EntityRepository
{


    public function findPublicityWithFineshed($date){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
            FROM EventsBundle:Publicity p
            WHERE  p.dateFin<=:current'
            )
            ->setParameter('current', $date)
            ->getResult();
    }




}
