list_publication:
    path:     /publications
    defaults: { _controller: ForumBundle:Publication:listPub }

list_complaint:
    path:     /complaints
    defaults: { _controller: ForumBundle:Reclamation:recList }

list_complaint2:
  path:     /complaintsDash
  defaults: { _controller: ForumBundle:Reclamation:listRec }

blog:
    path:     /blog
    defaults: { _controller: ForumBundle:Publication:frontBlog }

blog-single:
    path:     /blog-single
    defaults: { _controller: ForumBundle:Reclamation:addRecFront }

pub_add:
    path:     /addPub
    defaults: { _controller: ForumBundle:Publication:addPub }

blog_add:
    path:     /addPubF
    defaults: { _controller: ForumBundle:Publication:addPubFront }

pub_update:
    path:     /updatePub/{id}
    defaults: { _controller: ForumBundle:Publication:updatePub }

pub_detailed:
  path:     /detailedPub/{id}
  defaults: { _controller: ForumBundle:Publication:showPub }

pub_detailedDash:
  path:     /detailedPubDash/{id}
  defaults: { _controller: ForumBundle:Publication:showPubDash }

pub_delete:
    path:     /deletePub/{id}
    defaults: { _controller: ForumBundle:Publication:deletePub }

blog_update:
  path:     /updateblog/{id}
  defaults: { _controller: ForumBundle:Publication:updatePubFront }

blog_delete:
  path:     /deleteblog/{id}
  defaults: { _controller: ForumBundle:Publication:deletePubFront }

rec_update:
  path:     /updateRec/{id}
  defaults: { _controller: ForumBundle:Reclamation:updateRecFront }

rec_delete:
  path:     /deleteRec/{id}
  defaults: { _controller: ForumBundle:Reclamation:deleteRecFront }


handled_rec:
  path:     /handleRec/{id}
  defaults: { _controller: ForumBundle:Reclamation:handledFront }

pin_pub:
  path:     /pinPub/{id}
  defaults: { _controller: ForumBundle:Publication:pinPub }

close_pub:
  path:     /closePub/{id}
  defaults: { _controller: ForumBundle:Publication:closePub }

check:
  path:     /check/{id}
  defaults: { _controller: ForumBundle:Publication:check }

closeDash_pub:
  path:     /closePubDash/{id}
  defaults: { _controller: ForumBundle:Publication:closePubDash }

handled_rec2:
  path:     /handle/{id}
  defaults: { _controller: ForumBundle:Reclamation:handled }

add_rec:
  path:     /addRec
  defaults: { _controller: ForumBundle:Reclamation:addRec }

more_pub:
  path:     /morePubs/{user}
  defaults: { _controller: ForumBundle:Publication:morePubs }

add_comment:
  path:     /addComment
  defaults: { _controller: ForumBundle:Publication:addComment }

delete_comment:
  path:     /deleteComment/{id}
  defaults: { _controller: ForumBundle:Publication:deleteComment }


rechercher:
  path:     /recherche
  defaults: { _controller: ForumBundle:Publication:recherche}