#services:
 # my.handler.session_idle:
  #  class: ForumBundle\Handler\SessionIdleHandler
   # arguments: ["@session", "@security.authorization_checker", "@router", %session_max_idle_time%]
    #tags:
     # - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
