<?php

namespace TrainingBundle\Repository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
