<?php

namespace TrainingBundle\Repository;

/**
 * EntrainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrainementRepository extends \Doctrine\ORM\EntityRepository
{
}
