<?php

namespace ForumBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

}
