<?php

namespace ProductBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduit($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ProductBundle:Produit p
                WHERE p.promotion =:id '
            )
            ->setParameter('id',$id)
            ->getSingleResult();
    }
}
